### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by guanzo**
Update copy and design as per https://www.notion.so/pl-strflt/Copy-review-e1b84b9f8fdb40dbbb8feca4f8e4c46f

Leave feedback on Figma: https://www.figma.com/file/VfHsvM694SuzixeygNqLcU/Saturn-Website?type=design&node-id=0-1&mode=design&t=TmkEBqOcEpjffSBl-0

I stopped using the mdx files and added text to the JSX itself. mdx is too complicated and had questionable benefit.

### CODE REVIEW

**Comment by guanzo** [comment]
Current fleek preview at: https://bafybeib57b5epo3oh7kwsllnyzdqy3wkccrphetba5uz3bpchkzbhnrfsa.on.fleek.co/

**Comment by guanzo** [comment]
Current fleek PR preview at: https://bafybeibqtmfa57hrfqeej6oux4vabykmfb3vsds4ooyco4xxjwzdqardsy.on.fleek.co/

**Comment by wilkyr31d** [comment]
Needs to change the "How does it work" to "How it works"

**Comment by wilkyr31d** [comment]
"Start now for free" button doesn't work

**Comment by wilkyr31d** [comment]
"TODO: Placeholder Image" showing instead of images.

**Comment by wilkyr31d** [comment]
The phrase "How does it work" appears multiple times, so need to do find/replace to "How it works"

**Comment by wilkyr31d** [comment]
Under "Integrate Saturn", "A step-by-step guide will assist you with the integration process." <- is that supposed to be a link to the step-by-step-guide? Is anything around here supposed to be a link?

**Comment by prodalex** [comment]
> Under "Integrate Saturn", "A step-by-step guide will assist you with the integration process." <- is that supposed to be a link to the step-by-step-guide? Is anything around here supposed to be a link?

This will be the SW installation guide inside the portal

**Comment by guanzo** [comment]
preview: https://bafybeidprcidv5yqoyueqkpfixinvztqikzpj7mxk3om3usjbtir4a4exe.on.fleek.co/

**Comment by guanzo** [comment]
preview: https://bafybeidebcjfdg3ztxbrmhjdfuvyh753q5skhnph7nylgs6ofaqn6mu42e.on.fleek.co/node-providers

**Comment by wilkyr31d** [comment]
@guanzo @prodalex : To me, I keep thinking "Join the Community" should be a hyperlink until I realize (again) that it's really a CTA heading, but it's a little odd because there's another CTA heading just above it ("Get in touch!!"). My thought is just replace "Get in touch!" with "Join the Community!", and have only the 1 CTA, followed by the normal text, followed by the Slack and Twitter links

Screenshot 2023-11-07 at 4 46 42 PM

**Comment by wilkyr31d** [comment]
@guanzo @prodalex - should the Twitter link be changed to X?

**Comment by wilkyr31d** [comment]
@prodalex - should we remove the roadmap since it's out of date?

**Comment by wilkyr31d** [comment]
@guanzo - links to portal currently go to portal-test; how are you tracking getting those changed over to prod?

**Comment by prodalex** [comment]
> @prodalex - should we remove the roadmap since it's out of date?

I would keep it for now and then update as we go

**Comment by prodalex** [comment]
> @guanzo @prodalex - should the Twitter link be changed to X?

Can do! good catch

**Comment by guanzo** [comment]
> @guanzo - links to portal currently go to portal-test; how are you tracking getting those changed over to prod?

the links are created with environment variables, so when we build the site for prod it'll use the prod URLs.

**Comment by guanzo** [comment]
> should the Twitter link be changed to X?

@wilkyr31d X logo next to "X" text looks odd heh.. thoughts?

image

**Comment by guanzo** [comment]
addressed feedback

preview: https://bafybeiahtvmdpttkays3bqpgwdwi6gqo5x4hd4dqw7i6xp337hodu5lmsm.on.fleek.co/

**Pull request merged**
